services:
  # See https://render.com/docs/blueprint-spec for more info on render blueprints
  - type: web
    name: code4Africa
    env: python
    plan: standard
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:server"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
        
